### ISSUE TITLE
Not sure what the issue is...

### ISSUE THREAD

**Issue by spyderdyne** [cacois/python-configparser-examples#2]
I am attempting to use your examples to pull variables from an .INI file.  I am attempting to follow you well written examples and after spending a large amount of time reformatting my entire config file and my entire script, it isn't working.

config file:

[DEFAULT]

status_message = 'Parsing default configuration data...'

...

[OTHERSECTIONNAME]

Python attempt 1 code:
# Import global configuration values

global_config = ConfigParser.RawConfigParser()
global_config.read('environments.ini')
# DEBUG - Prove that the config file is accessible

print global_config.get('DEFAULT')

attempt 1 error:

print global_config.get('DEFAULT')
TypeError: get() takes exactly 3 arguments (2 given)

Python attempt 2 code:
# Import global configuration values

global_config = ConfigParser.RawConfigParser()
global_config.read('environments.ini')
# DEBUG - Prove that the config file is accessible

print global_config.get('DEFAULT', 'status_message')

Attempt 2 error:

print global_config.get('DEFAULT', 'status_message')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 326, in get
ConfigParser.NoOptionError: No option 'status_message' in section: 'DEFAULT'

This is at top level just after the import statements.  I attempted to create a class to set this variable but could not figure out how to access it from other classes and methods.  This seems very simple.  Is this syntax not Python 2.7 compatible maybe?

**Comment by cacois** [comment]
No idea, but the code has been updated for python3, so i'm closing this issue (which was python2 related). 

cheers!
